version: '3.3'
services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    image: nginx:1.13.3-alpine
    restart: always
    depends_on:
      - php
    volumes:
      - ./conf/nginx/api.conf:/etc/nginx/conf.d/api.conf:rw
      - ./logs:/var/log/nginx
    labels:
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST_API}"

  php:
    image: lcidral/php:7.2.4-fpm-xdebug-alpine
    restart: always
    depends_on:
      - reverse-proxy
    volumes:
      - ~/.composer/cache:/root/.composer/cache
      - ./:/var/www/html
      - ./conf/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./conf/php/docker-php-ext-sendmail.ini:/usr/local/etc/php/conf.d/docker-php-ext-sendmail.ini
      - ./conf/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    env_file:
      - ./conf/docker/environment.config

  mariadb:
    image: mariadb:10.1.26
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      VIRTUAL_HOST: '${DB_HOST}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'

  mail:
    image: lcidral/mailcatcher.dev:latest
    ports:
      - '1025:1025'
      - '1080:1080'
